language: go
go:
 - 1.14.4
 - tip

before_install:
 - go get -u github.com/mattn/goveralls
 - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
 - make lint
 - make unit-test

after_success:
 - goveralls -coverprofile=coverage.out -service=travis-ci
