language: go
go: 
 - 1.7
 - 1.14.4
 - tip

before_install:
 - go get -u github.com/mattn/goveralls
 - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
 - make unit-test
 - goveralls -coverprofile=coverage.out -service=travis-ci 